more work

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2300,6 +2300,13 @@ VERSION=2.0
 
 
 
+if test $host_os = darwin; then
+	cat >>confdefs.h <<\_ACEOF
+#define __DARWIN__ 1
+_ACEOF
+
+fi
+
 
 # Check whether --enable-shared or --disable-shared was given.
 if test "${enable_shared+set}" = set; then
@@ -3848,7 +3855,7 @@ else
 fi
 
 
-enable_dlopen=no
+enable_dlopen=yes
 enable_win32_dll=no
 
 # Check whether --enable-libtool-lock or --disable-libtool-lock was given.
@@ -3863,7 +3870,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3866 "configure"' > conftest.$ac_ext
+  echo '#line 3873 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4391,7 +4398,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:4394: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:4401: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6203,7 +6210,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6206 "configure"
+#line 6213 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6301,7 +6308,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6304 "configure"
+#line 6311 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7037,6 +7044,10 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 
 
 
+if test -n $lt_cv_dlopen_libs ; then
+	LIBS=$lt_cv_dlopen_libs
+fi
+
 # Find a good install program.  We prefer a C program (faster),
 # so one script is as good as another.  But avoid the broken or
 # incompatible versions:
@@ -7476,6 +7487,67 @@ if test $poco_cv_gcc_pthread = yes; then
 	poco_threads=""
 	CFLAGS="$CFLAGS -pthread"
 else
+	echo "$as_me:$LINENO: checking if compiler recognizes -mt" >&5
+echo $ECHO_N "checking if compiler recognizes -mt... $ECHO_C" >&6
+if test "${poco_cv_cc_mt+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_save_CFLAGS=$CFLAGS
+		CFLAGS="$CFLAGS -mt"
+
+
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+		cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <pthread.h>
+int
+main ()
+{
+void *p = pthread_create;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  poco_cv_cc_mt=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+poco_cv_cc_mt=no
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+		CFLAGS=$ac_save_CFLAGS
+
+fi
+echo "$as_me:$LINENO: result: $poco_cv_cc_mt" >&5
+echo "${ECHO_T}$poco_cv_cc_mt" >&6
+	if test $poco_cv_cc_mt = yes; then
+		CFLAGS="$CFLAGS -mt";
+	fi
 	echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
 echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6
 if test "${ac_cv_lib_pthread_pthread_create+set}" = set; then
@@ -7586,7 +7658,7 @@ fi
 fi
 
 if test -n $poco_threads ; then
-	LIBS=-lpthread
+	LIBS="-lpthread $LIBS"
 fi
 
 echo "$as_me:$LINENO: checking for library containing fabs" >&5
