25. Preliminary RTAI/user-space support. posterLib requires a more      complicated implementation: as of now, posters can be shared between      RTAI-tasks and linux processes but this breaks the real-time      properties of RTAI-tasks.  24. Added taskDelete() regression test.  23. Added --with-debug option to configure script. It allows the      selection of independant components to debug.  22. Added h2devClean() in comLib. This was previously defined in h2.c      but it was problematic for user-space RTAI version. Bumped comLib      minor.  21. Added taskOptionsSet()/taskOptionsGet() in taskLib and a new task's      option bit PORTLIB_UNPRIVILEGED. This is used internally by comLib      for user space communication under RTAI. Bumped portLib minor.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -469,7 +469,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT PACKAGE VERSION LN_S ECHO RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP EGREP LIBTOOL RTAI_INCLUDES OSAPI INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA MKDEP RPCGEN RPCGEN_C PURIFY HAS_X XCPPFLAGS XLDFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT PACKAGE VERSION LN_S ECHO RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP EGREP LIBTOOL RTAI_INCLUDES OSAPI INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA MKDEP RPCGEN RPCGEN_C PURIFY HAS_X XCPPFLAGS XLDFLAGS COMLIB_COMPATSRC LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1027,6 +1027,8 @@ Optional Packages:
                           RTAI headers are in DIR
   --with-purify           configure to postprocess with purify
   --with-x                use the X Window System
+  --with-debug=all task h2dev smmem h2evn mbox gcom
+                          print debugging information at run-time
 
 Some influential environment variables:
   CC          C compiler command
@@ -4172,7 +4174,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4175 "configure"' > conftest.$ac_ext
+  echo '#line 4177 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4744,7 +4746,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:4747: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:4749: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6708,7 +6710,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6711 "configure"
+#line 6713 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6806,7 +6808,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6809 "configure"
+#line 6811 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9546,6 +9548,163 @@ fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 
+
+for ac_func in fnmatch
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define $ac_func innocuous_$ac_func
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef $ac_func
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+char (*f) () = $ac_func;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != $ac_func;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_var=no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+
+else
+
+	COMLIB_COMPATSRC="${COMLIB_COMPATSRC} fnmatch.c"
+
+fi
+done
+
+
+
+
+
+
+# Check whether --with-debug or --without-debug was given.
+if test "${with_debug+set}" = set; then
+  withval="$with_debug"
+  opt_debug=$withval
+else
+  opt_debug=
+fi;
+
+if test "x$opt_debug" = "xall"; then
+   opt_debug="task h2dev smmem h2evn mbox gcom"
+fi
+for dopt in "$opt_debug"; do
+	test -z "$dopt" && break
+
+	case "$dopt" in
+	   task)	cat >>confdefs.h <<\_ACEOF
+#define PORTLIB_DEBUG_TASKLIB 1
+_ACEOF
+ ;;
+
+	   h2dev)	cat >>confdefs.h <<\_ACEOF
+#define COMLIB_DEBUG_H2DEVLIB 1
+_ACEOF
+ ;;
+	   smmem)	cat >>confdefs.h <<\_ACEOF
+#define COMLIB_DEBUG_SMMEMLIB 1
+_ACEOF
+ ;;
+	   h2evn)	cat >>confdefs.h <<\_ACEOF
+#define COMLIB_DEBUG_H2EVNLIB 1
+_ACEOF
+ ;;
+	   mbox)	cat >>confdefs.h <<\_ACEOF
+#define COMLIB_DEBUG_MBOXLIB 1
+_ACEOF
+ ;;
+	   gcom)	cat >>confdefs.h <<\_ACEOF
+#define COMLIB_DEBUG_GCOMLIB 1
+_ACEOF
+ ;;
+
+	esac
+done
+
+
+
           ac_config_headers="$ac_config_headers src/pocolibs-config.h"
 
                                                                                                                                   ac_config_files="$ac_config_files Init.make Makefile include/Makefile src/portLib/Makefile src/errorLib/Makefile src/errorLib/h2addErrno src/comLib/Makefile src/posterLib/Makefile src/posterLib/posterServ/Makefile src/h2/Makefile src/shell/Makefile src/xes/Makefile src/regress/Makefile"
@@ -10210,6 +10369,7 @@ s,@PURIFY@,$PURIFY,;t t
 s,@HAS_X@,$HAS_X,;t t
 s,@XCPPFLAGS@,$XCPPFLAGS,;t t
 s,@XLDFLAGS@,$XLDFLAGS,;t t
+s,@COMLIB_COMPATSRC@,$COMLIB_COMPATSRC,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
